{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: catenax-managed-identity-wallets-ingress
  namespace: {{ .Values.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/server-snippet: |
          location ~* /list-credential/ {
              deny all;
              return 403;
            }

    # If you encounter a redirect loop or are getting a 307 response code
    # then you need to force the nginx ingress to connect to the backend using HTTPS.
    #
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
    - host: {{ .Values.certificate.host }}
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: catenax-managed-identity-wallets
                port:
                  number: 8080
    # TODO Acapy inbound calls should be forwared to 8000 and 8003. This is related 
    # to the values acapy.endorser.endpointUrl and acapy.mt.endpointUrl.
    # Mabye a new host is required to achive this
  tls:
    - hosts:
        - {{ .Values.certificate.host }}
      secretName: tls-secret
{{- end}}