{{- if not .Values.isLocal }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "managed-identity-wallets.fullname" . }}-acapy
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  acapy-admin-api-key: {{ .Values.acapy.secret.apikey | quote }}
  acapy-agent-wallet-seed: {{ .Values.acapy.secret.walletseed | quote }}
  acapy-db-account: {{ .Values.acapy.secret.dbaccount | quote }}
  acapy-db-admin: {{ .Values.acapy.secret.dbadminuser | quote }}
  acapy-db-admin-password: {{ .Values.acapy.secret.dbadminpassword | quote }}
  acapy-db-password: {{ .Values.acapy.secret.dbpassword | quote }}
  acapy-jwt-secret: {{ .Values.acapy.secret.jwtsecret | quote }}
  acapy-wallet-key: {{ .Values.acapy.secret.walletkey | quote }}
{{- end}}
{{- if not .Values.isLocal }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "managed-identity-wallets.fullname" . }}-acapypostgresql
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password: {{ .Values.acapypostgresql.secret.password | quote }}
  postgres-password: {{ .Values.acapypostgresql.secret.postgrespassword | quote }}
  user: {{ .Values.acapypostgresql.secret.user | quote }}
{{- end}}
{{- if not .Values.isLocal }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "managed-identity-wallets.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password: {{ .Values.postgresql.secret.password | quote }}
  postgres-password: {{ .Values.postgresql.secret.postgrespassword | quote }}
  user: {{ .Values.postgresql.secret.user | quote }}
{{- end}}
{{- if not .Values.isLocal }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "managed-identity-wallets.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  cx-db-jdbc-url: {{ .Values.managedIdentityWallets.secret.jdbcurl | quote }}
  cx-auth-client-id: {{ .Values.managedIdentityWallets.secret.authclientid | quote }}
  cx-auth-client-secret: {{ .Values.managedIdentityWallets.secret.authclientsecret | quote }}
  bpdm-auth-client-id: {{ .Values.managedIdentityWallets.secret.bpdmauthclientid | quote }}
  bpdm-auth-client-secret: {{ .Values.managedIdentityWallets.secret.bpdmauthclientsecret | quote }}
{{- end}}
