auth:
  jwksUrl: "https://centralidp-pen.dev.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/certs"
  issuerUrl: "https://centralidp-pen.dev.demo.catena-x.net/auth/realms/CX-Central"
  redirectUrl: "https://managed-identity-wallets-pen.dev.demo.catena-x.net/callback"
datapool:
  url: "https://catenax-bpdm-dev.demo.catena-x.net"
  authUrl: "https://centralidp.dev.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token"
image:
  tag: "latest-develop"
revocationService:
  baseUrlForCredentialList: "https://managed-identity-wallets.pen.demo.catena-x.net/api/credentials/"
  clientIssuanceApiUrl: "${SSI_SERVICE_URL:-http://localhost:8080}" 
acapy:
  logLevel: "DEBUG"
  ledgerUrl: "http://dev.greenlight.bcovrin.vonx.io"
  endpointUrl: "https://managed-identity-wallets-pen.dev.demo.catena-x.net:8000/"
  databaseHost: "product-managed-identity-wallets-pen-acapypostgresql"
  secret:
    name: "catenax-managed-identity-wallets-acapy-secrets"
    path: "managed-identity-wallets/data/pen/catenax-managed-identity-wallets-acapy-secrets"
certificate:
  host: "managed-identity-wallets-pen.dev.demo.catena-x.net"
managedIdentityWallets:
  secret:
    name: "catenax-managed-identity-wallets-secrets"
    path: "managed-identity-wallets/data/pen/catenax-managed-identity-wallets-secrets"
postgresql:
  secret:
    name: "product-managed-identity-wallets-postgresql"
    path: "managed-identity-wallets/data/pen/postgres-managed-identity-wallets-secret-config"
acapypostgresql:
  secret:
    name: "product-managed-identity-wallets-acapy-postgresql"
    path: "managed-identity-wallets/data/pen/postgres-acapy-secret-config"