auth:
  jwksUrl: "https://centralidp.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/certs"
  issuerUrl: "https://centralidp.demo.catena-x.net/auth/realms/CX-Central"
  redirectUrl: "https://managed-identity-wallets.int.demo.catena-x.net/callback"
datapool:
  url: "https://catenax-bpdm-beta.demo.catena-x.net"
  authUrl: "https://centralidp.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token"
revocationService:
  baseUrlForCredentialList: "https://managed-identity-wallets.beta.demo.catena-x.net/api/credentials/"
  clientIssuanceApiUrl: "http://localhost:8080"
acapy:
  endpointUrl: "https://managed-identity-wallets.beta.demo.catena-x.net:8000/"
  secret:
    name: "catenax-managed-identity-wallets-acapy-secrets"
    path: "managed-identity-wallets/data/int/catenax-managed-identity-wallets-acapy-secrets"
certificate:
  host: "managed-identity-wallets.beta.demo.catena-x.net"
managedIdentityWallets:
  secret:
    name: "catenax-managed-identity-wallets-secrets"
    path: "managed-identity-wallets/data/beta/catenax-managed-identity-wallets-secrets"
postgresql:
  secret:
    name: "product-managed-identity-wallets-postgresql"
    path: "managed-identity-wallets/data/beta/postgres-managed-identity-wallets-secret-config"
acapypostgresql:
  secret:
    name: "product-managed-identity-wallets-acapy-postgresql"
    path: "managed-identity-wallets/data/beta/postgres-acapy-secret-config"